### PR TITLE
Update writing-models-to-disk.rst

### PR DESCRIPTION
**Pull request by serkkz**
Added import from the egg library, the code can now be run.

### CODE REVIEW

**Comment by rdb** [comment]
The point of the manual is not to be a repository of self-contained examples.  That's what the sample programs are for.  If an import is missing I am happy to add it, but creating a ShowBase subclass is entirely unnecessary to demonstrate how to write an egg file to disk.

**Comment by serkkz** [comment]
I don't think a self-contained example is a bad thing, it doesn't have any logic. I was always surprised when I read the manual that you can't quickly check the code.

However, saving the model has mystical problems. You can check it yourself.

**Comment by rdb** [comment]
The problem I see is the lack of `<CoordinateSystem> { Z-up }`.  This can be assigned on the EggData object.

**Comment by serkkz** [comment]
How do you like this option?

**Review by rdb — CHANGES_REQUESTED** [review]
Good, but:
* Instead of 1, use `CSZupRight` (imported from `panda3d.core`)
* Does `data.setCoordinateSystem(CSZupRight)` not work?

**Comment by serkkz** [comment]
How would it be more logical to use the egg library? Yes, it works perfectly.
To be honest, I don't quite understand why import a number? This is an int class.
`<class 'int'>`
For me, this is completely absurd.

**Comment by serkkz** [comment]
Replaced.

**Review by rdb — APPROVED** [review]
Thanks.

**Comment by rdb** [comment]
> To be honest, I don't quite understand why import a number? This is an int class.
> `<class 'int'>`
> For me, this is completely absurd.

Yes, it's a side-effect of how enums work in C++ and are exposed to Python..

However, with new C++11-style "enum classes", this can be improved, because they can be mapped to Python enums better.  We should use these new enum classes for new enumerations going forward.

**Pull request merged**
