### PR TITLE
Fix more typos

### PR DESCRIPTION
**Pull request by Epihaius**
More typos have been corrected.

### CODE REVIEW

**Review by rdb — APPROVED** [review]
Thank you!

**Review by rdb — CHANGES_REQUESTED** [review]
It looks like you altered the table structure, see this lint error:
```
/home/runner/work/panda3d-docs/panda3d-docs/programming/render-attributes/materials.rst:138: D000 Malformed table.
```

**Comment by Epihaius** [comment]
The table structure seems to be fixed now, but Lint still doesn't seem to be happy...
Is there still a problem with my changes?

**Comment by rdb** [comment]
It's a linkcheck that failed because an SSL certificate expired on one of the many sites we link to.  Not related to your changes.

Committed in a141308ab59a2c871355c4e2747c3490e52b7cf5. Thanks!

**Pull request closed without merging**
