### PR TITLE
Update starting-panda3d.rst

### PR DESCRIPTION
**Pull request by malatindez**

### CODE REVIEW

**Comment by rdb** [comment]
`ppython` is shipped with the SDK and recommended because it ensures that the version of Python that is shipped with Panda3D is being used.

However, because we now support installation via pip, and we now install Panda to the Windows Registry so that it's available to any Python installation, I suppose there is no more reason to recommend ppython, hmm.

**Comment by serkkz** [comment]
In fact, installation in the registry is annoying, it would be better if just .reg files were supplied with Panda, for example, to register the decompressor .pz and so on.

In Windows, this is useless ,for example, I can't run old versions of Panda3D without problems.

**Comment by rdb** [comment]
We could make it an optional setting in the installer.

**Comment by serkkz** [comment]
Yes, but it won't fix the problem. There are many mysterious problems, for example I couldn't install Numpy until I got rid of Panda3D.

**Pull request closed without merging**
