### PR TITLE
Replaced some screenshots

### PR DESCRIPTION
**Pull request by Shadow2121**
As mentioned in #48 , I updated some screenshots in "installation-windows" page of web-site.

### CODE REVIEW

**Comment by Shadow2121** [comment]
So, it has to complete all checks successfully to merge this request?

**Comment by rdb** [comment]
No, the check suite is currently failing for a different reason, don't worry about it.

**Comment by Shadow2121** [comment]
> 
> 
> No, the check suite is currently failing for a different reason, don't worry about it.

Ok ,thank you

**Comment by rdb** [comment]
Thanks a lot for the screenshots!  I have run them through optipng and committed them.

I did edit out the FPS meter in one of the screenshots since it's not part of Panda and might confuse some users.

**Pull request closed without merging**
